services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bankcards
      SPRING_DATASOURCE_USERNAME: bankcards
      SPRING_DATASOURCE_PASSWORD: bankcards
      SPRING_PROFILES_ACTIVE: dev
      APP_SECURITY_JWT_SECRET: please-change-me-to-32-bytes-minimum-secret-key........
      JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=75.0
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: bankcards
      POSTGRES_PASSWORD: bankcards
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankcards -d bankcards"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data: