server:
  port: ${SPRING_APP_PORT}

spring:
  application:
    name: ${SPRING_APP_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SPRING_SHOW_SQL}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: ${LIQUIBASE_ENABLED}
    change-log: classpath:db/migration/db.migration-master.yaml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    cors:
      mappings:
        "/api/**":
          allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
          allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
          allowed-headers: "*"
          exposed-headers: Authorization,Content-Type
          allow-credentials: true
          max-age: 3600

# Настройки Swagger / OpenAPI (springdoc)
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# Пользовательские настройки безопасности и JWT
app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-in-prod}
      expiration-ms: ${JWT_EXPIRATION_MS:3600000}
      issuer: bank-cards
      header: Authorization
      prefix: Bearer
    cors:
      enabled: true
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
      allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
      allowed-headers: "*"
      exposed-headers: Authorization,Content-Type
      allow-credentials: true
      max-age: 3600

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    liquibase: INFO